version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - share-network
volumes:
  redis-data:
networks:
  share-network:
    external: true
